name: ERP Stock Reports

on:
  workflow_dispatch:
  schedule:
    - cron: '50 4 * * *'   # 10:20 AM IST (Tamil Nadu)
    - cron: '55 4 * * *'   # 10:25 AM IST (Tamil Nadu)
jobs:
  stock-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run Closing Stock
        if: github.event.schedule == '50 4 * * *'
        env:
          ERP_USERNAME: ${{ secrets.ERP_USERNAME }}
          ERP_PASSWORD: ${{ secrets.ERP_PASSWORD }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python closing_stock.py

      - name: Run Opening Stock
        if: github.event.schedule == '55 4 * * *'
        env:
          ERP_USERNAME: ${{ secrets.ERP_USERNAME }}
          ERP_PASSWORD: ${{ secrets.ERP_PASSWORD }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python opening_stock.py